# Generated by Django 3.0.5 on 2020-07-02 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75, verbose_name='Nome')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Consulta')),
                ('periodo', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1, verbose_name='Período')),
                ('percentual_assertividade_prognostico', models.FloatField(verbose_name='Percentual de Assertividade do Prognóstico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=8, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ('logradouro', 'bairro'),
            },
        ),
        migrations.CreateModel(
            name='Especializacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Especialização',
                'verbose_name_plural': 'Especializações',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('dataNasc', models.DateField(verbose_name='Data de Nascimento')),
                ('crm', models.CharField(max_length=20, verbose_name='CRM')),
                ('especializacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Especializacao', verbose_name='Especialização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='MedicoUnidadeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaPeriodoTrabalho', models.CharField(max_length=500, verbose_name='Dias e Período de Trabalho')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Médico - Unidade de Saúde',
                'verbose_name_plural': 'Médicos - Unidades de Saúde',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomecsv', models.CharField(max_length=100, verbose_name='Nome CSV')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintomas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('PS', 'Posto de Saúde'), ('UBS', 'Centro de Saúde/Unidade Básica de Saúde'), ('PC', 'Policlínica'), ('HG', 'Hospital Geral'), ('HE', 'Hospital Especializado'), ('UM', 'Unidade Mista'), ('PSG', 'Pronto Socorro Geral'), ('PSE', 'Pronto Socorro Especializado'), ('CI', 'Consultório Isolado'), ('UMF', 'Unidade Móvel Fluvial'), ('CE', 'Clínica Especializada/Amb. Especializado'), ('USADT', 'Unidade de Serviço de Apoio a Diagnose e Terapia'), ('UMT', 'Unidade Móvel Terrestre'), ('UMNPAUE', 'Unidade Móvel de Nível Pré-hospitalar na Área de Urgência e Emergência'), ('HDI', 'Hospital/Dia-Isolado')], max_length=10, verbose_name='Tipo')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Endereco', verbose_name='Endereço')),
                ('medicos', models.ManyToManyField(through='app.MedicoUnidadeSaude', to='app.Medico', verbose_name='Médicos')),
            ],
            options={
                'verbose_name': 'Unidade de Saúde',
                'verbose_name_plural': 'Unidades de Saúde',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Prognostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.FloatField(verbose_name='Percentual')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Consulta', verbose_name='Consulta')),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doenca', verbose_name='Doença')),
            ],
            options={
                'verbose_name': 'Prognóstico',
                'verbose_name_plural': 'Prognósticos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('dataNasc', models.DateField(verbose_name='Data de Nascimento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='medicounidadesaude',
            name='unidadeSaude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UnidadeSaude', verbose_name='Unidade de Saúde'),
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ('sigla',),
            },
        ),
        migrations.CreateModel(
            name='EspecializacaoDoenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doenca', verbose_name='Doença')),
                ('especializacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Especializacao', verbose_name='Especialização')),
            ],
            options={
                'verbose_name': 'Especialização - Doença',
                'verbose_name_plural': 'Especializações - Doenças',
            },
        ),
        migrations.AddField(
            model_name='doenca',
            name='especializacoes',
            field=models.ManyToManyField(through='app.EspecializacaoDoenca', to='app.Especializacao', verbose_name='Especializações'),
        ),
        migrations.CreateModel(
            name='ConsultaSintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Consulta', verbose_name='Consulta')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sintoma', verbose_name='Sintoma')),
            ],
            options={
                'verbose_name': 'Consulta - Sintoma',
                'verbose_name_plural': 'Consultas - Sintomas',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Medico', verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='prognosticos',
            field=models.ManyToManyField(through='app.Prognostico', to='app.Doenca', verbose_name='Prognóstico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='sintomas',
            field=models.ManyToManyField(through='app.ConsultaSintoma', to='app.Sintoma', verbose_name='Sintomas'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='unidadeSaude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UnidadeSaude', verbose_name='Unidade de Saúde'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estado', verbose_name='Estado'),
        ),
    ]
