# Generated by Django 3.0.5 on 2020-07-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicounidadesaude',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Reprovado')], default='P', max_length=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
