# Generated by Django 3.0.5 on 2020-07-08 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_medicounidadesaude_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicounidadesaude',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Recusado')], max_length=1, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='AdminUnidadeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('dataNasc', models.DateField(verbose_name='Data de Nascimento')),
                ('unidadeSaudeResponsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UnidadeSaude', verbose_name='Unidade de Saúde')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminUnidadeSaude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador de Unidade de Saúde',
                'verbose_name_plural': 'Administrador de Unidades de Saúde',
                'ordering': ('nome',),
            },
        ),
    ]
