# Generated by Django 3.0.5 on 2020-07-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200701_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='unidadesSaude',
        ),
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.CharField(default='', max_length=20, verbose_name='CRM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadesaude',
            name='medicos',
            field=models.ManyToManyField(through='app.MedicoUnidadeSaude', to='app.Medico', verbose_name='Médicos'),
        ),
    ]
