# Generated by Django 3.0.5 on 2020-07-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200708_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente')], default='', max_length=1, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultasintoma',
            name='possui',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (-1, '-1')], default=0, verbose_name='Possui'),
            preserve_default=False,
        ),
    ]
