# Generated by Django 3.0.5 on 2020-08-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_consulta_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='app.Doenca', verbose_name='Diagnóstico'),
        ),
    ]
