# Generated by Django 3.0.5 on 2020-08-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_consulta_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(verbose_name='Peso (kg)')),
                ('altura', models.FloatField(verbose_name='Altura (m)')),
                ('fuma', models.BooleanField(verbose_name='Fuma?')),
                ('qtdCigarrosDia', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Cigarros (Dia)')),
                ('bebe', models.BooleanField(verbose_name='Bebe?')),
                ('freqBebeDiasSemana', models.IntegerField(blank=True, null=True, verbose_name='Frequência que Bebe (Dias da Semana)')),
                ('qualidadeAlimentacaoIngestaoAgua', models.IntegerField(choices=[(1, 'Boa'), (2, 'Regular'), (3, 'Ruim')], verbose_name='Qualidade da Alimentação e Ingestão de Água')),
                ('praticaAtividadeFisica', models.BooleanField(verbose_name='Pratica Atividades Físicas?')),
                ('tipoAtividadeFisica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Atividade Física')),
                ('freqAtividadeFisicaDiasSemana', models.IntegerField(blank=True, null=True, verbose_name='Frequência de Atividades Físicas (Dias da Semana)')),
                ('utilizaAnticoncepcional', models.BooleanField(verbose_name='Utiliza Anticoncepcional?')),
                ('anticoncepcionaisUtilizados', models.CharField(blank=True, max_length=100, null=True, verbose_name='Anticoncepcionais Utilizados')),
                ('realizouGestacoes', models.BooleanField(verbose_name='Realizou Gestações?')),
                ('ultimaGestacaoTempoMeses', models.IntegerField(blank=True, null=True, verbose_name='Tempo da Última Gestação (Meses)')),
                ('utilizaMedicamentos', models.BooleanField(verbose_name='Utiliza Medicamentos?')),
                ('medicamentosUtilizados', models.CharField(blank=True, max_length=150, null=True, verbose_name='Medicamentos utilizados')),
                ('alergias', models.BooleanField(verbose_name='Possui/Possuiu alergias?')),
                ('alergiasDesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alergias')),
                ('alteracoesCardiacas', models.BooleanField(verbose_name='Possui/Possui alterações cardíacas?')),
                ('alteracoesCardiacasDesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alterações Cardíacas')),
                ('pressaoAlta', models.BooleanField(verbose_name='Possui pressão alta?')),
                ('pressaoBaixa', models.BooleanField(verbose_name='Possui pressão baixa?')),
                ('disturbioCirculatorio', models.BooleanField(verbose_name='Possui/Possuiu distúrbios circulatório?')),
                ('disturbioCirculatorioDesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distúrbios circulatórios')),
                ('disturbioHormonal', models.BooleanField(verbose_name='Possui/Possuiu distúrbios hormonais?')),
                ('disturbioHormonalDesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distúrbios hormonais')),
                ('diabetes', models.BooleanField(verbose_name='Possui diabetes?')),
                ('tipoDiabetes', models.IntegerField(blank=True, choices=[(1, 'Tipo 1'), (2, 'Tipo 2'), (3, 'Gestacional')], null=True, verbose_name='Tipo de diabetes')),
                ('fezCirurgias', models.BooleanField(verbose_name='Realizou cirurgias?')),
                ('cirurgiasDesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cirurgias realizadas')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aguardando Exames'), ('F', 'Finalizada')], max_length=1, verbose_name='Status'),
        ),
    ]
