# Generated by Django 3.0.5 on 2020-08-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200829_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='anamnese',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Anamnese'),
            preserve_default=False,
        ),
    ]
