# Generated by Django 3.0.5 on 2020-08-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_consulta_anamnese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='anamnese',
        ),
    ]
