from django.db import models

# Create your models here.
class PrognosticoData(models.Model):
    NUM_CHOICES = ((0,'0'),
                   (1,'1'))

    comichao = models.IntegerField(choices=NUM_CHOICES, verbose_name="Comichão", default=0)
    erupcao_cutanea = models.IntegerField(choices=NUM_CHOICES, verbose_name="Erupção cutânea", default=0)
    erupcoes_cutaneas_nodais = models.IntegerField(choices=NUM_CHOICES, verbose_name="Erupções cutâneas nodais", default=0)
    espirros_continuos = models.IntegerField(choices=NUM_CHOICES, verbose_name="Espirros contínuos", default=0)
    calafrios = models.IntegerField(choices=NUM_CHOICES, verbose_name="Calafrios", default=0)
    arrepios = models.IntegerField(choices=NUM_CHOICES, verbose_name="Arrepios", default=0)
    dor_juntas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor nas juntas", default=0)
    dor_estomago = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor no estômago", default=0)
    acidez = models.IntegerField(choices=NUM_CHOICES, verbose_name="Acidez", default=0)
    ulceras_lingua = models.IntegerField(choices=NUM_CHOICES, verbose_name="Úlceras na língua", default=0)
    desgaste_muscular = models.IntegerField(choices=NUM_CHOICES, verbose_name="Desgaste muscular", default=0)
    vomito = models.IntegerField(choices=NUM_CHOICES, verbose_name="Vômito", default=0)
    queimacao_urinar = models.IntegerField(choices=NUM_CHOICES, verbose_name="Queimação ao urinar", default=0)
    sangue_urina = models.IntegerField(choices=NUM_CHOICES, verbose_name="Sangue na urina", default=0)
    fadiga = models.IntegerField(choices=NUM_CHOICES, verbose_name="Fadiga", default=0)
    ganho_peso = models.IntegerField(choices=NUM_CHOICES, verbose_name="Ganho de peso", default=0)
    ansiedade = models.IntegerField(choices=NUM_CHOICES, verbose_name="Ansiedade", default=0)
    maos_pes_frios = models.IntegerField(choices=NUM_CHOICES, verbose_name="Mãos e pés frios", default=0)
    mudanca_humor = models.IntegerField(choices=NUM_CHOICES, verbose_name="Mudança de humor", default=0)
    perda_peso = models.IntegerField(choices=NUM_CHOICES, verbose_name="Perda de peso", default=0)
    inquietacao = models.IntegerField(choices=NUM_CHOICES, verbose_name="Inquietação", default=0)
    letargia = models.IntegerField(choices=NUM_CHOICES, verbose_name="Letargia", default=0)
    mancha_garganta = models.IntegerField(choices=NUM_CHOICES, verbose_name="Manchas (brancas) na garganta", default=0)
    nivel_acucar_irregular = models.IntegerField(choices=NUM_CHOICES, verbose_name="Nível de açúcar irregular", default=0)
    tosse = models.IntegerField(choices=NUM_CHOICES, verbose_name="Tosse", default=0)
    febre_alta = models.IntegerField(choices=NUM_CHOICES, verbose_name="Febre alta", default=0)
    olhos_fundos = models.IntegerField(choices=NUM_CHOICES, verbose_name="Olhos fundos", default=0)
    falta_de_ar = models.IntegerField(choices=NUM_CHOICES, verbose_name="Falta de ar", default=0)
    suor = models.IntegerField(choices=NUM_CHOICES, verbose_name="Suor", default=0)
    desidratacao = models.IntegerField(choices=NUM_CHOICES, verbose_name="Desidratação", default=0)
    indigestao = models.IntegerField(choices=NUM_CHOICES, verbose_name="Indigestão", default=0)
    dor_cabeca = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor de cabeça", default=0)
    pele_amarelada = models.IntegerField(choices=NUM_CHOICES, verbose_name="Pele amarelada", default=0)
    urina_escura = models.IntegerField(choices=NUM_CHOICES, verbose_name="Urina escura", default=0)
    nausea = models.IntegerField(choices=NUM_CHOICES, verbose_name="Náusea", default=0)
    perda_apetite = models.IntegerField(choices=NUM_CHOICES, verbose_name="Perda de apetite", default=0)
    dor_atras_olhos = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor atrás dos olhos", default=0)
    dor_costas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor nas costas", default=0)
    constipacao = models.IntegerField(choices=NUM_CHOICES, verbose_name="Constipação", default=0)
    dor_abdominal = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor abdominal", default=0)
    diarreia = models.IntegerField(choices=NUM_CHOICES, verbose_name="Diarreia", default=0)
    febre_suave = models.IntegerField(choices=NUM_CHOICES, verbose_name="Febre suave", default=0)
    urina_amarela = models.IntegerField(choices=NUM_CHOICES, verbose_name="Urina amarela", default=0)
    amarelamento_olhos = models.IntegerField(choices=NUM_CHOICES, verbose_name="Amarelamento dos olhos", default=0)
    falencia_aguda_figado = models.IntegerField(choices=NUM_CHOICES, verbose_name="Falência aguda do fígado", default=0)
    inchaco_estomago = models.IntegerField(choices=NUM_CHOICES, verbose_name="Inchaço no estômago", default=0)
    linfonodos_aumentados = models.IntegerField(choices=NUM_CHOICES, verbose_name="Linfonodos aumentados", default=0)
    mal_estar = models.IntegerField(choices=NUM_CHOICES, verbose_name="Mal estar", default=0)
    visao_borrada_distorcida = models.IntegerField(choices=NUM_CHOICES, verbose_name="Visão borrada e/ou distorcida", default=0)
    catarro = models.IntegerField(choices=NUM_CHOICES, verbose_name="Catarro", default=0)
    irritacao_garganta = models.IntegerField(choices=NUM_CHOICES, verbose_name="Irritação na garganta", default=0)
    vermelhidao_olhos = models.IntegerField(choices=NUM_CHOICES, verbose_name="Vermelhidão nos olhos", default=0)
    sinusite = models.IntegerField(choices=NUM_CHOICES, verbose_name="Sinusite", default=0)
    nariz_escorrendo = models.IntegerField(choices=NUM_CHOICES, verbose_name="Nariz escorrendo", default=0)
    nariz_entupido = models.IntegerField(choices=NUM_CHOICES, verbose_name="Nariz entupido", default=0)
    dor_peito = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor no peito", default=0)
    fraqueza_membros = models.IntegerField(choices=NUM_CHOICES, verbose_name="Fraqueza nos membros (superiores e/ou inferiores)", default=0)
    taquicardia = models.IntegerField(choices=NUM_CHOICES, verbose_name="Taquicardia", default=0)
    dor_ao_evacuar = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor ao evacuar", default=0)
    dor_regiao_anal = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor na região anal", default=0)
    sangue_fezes = models.IntegerField(choices=NUM_CHOICES, verbose_name="Sangue nas fezes", default=0)
    irritacao_anus = models.IntegerField(choices=NUM_CHOICES, verbose_name="Irritação no ânus", default=0)
    dor_pescoco = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor no pescoço", default=0)
    tontura = models.IntegerField(choices=NUM_CHOICES, verbose_name="Tontura", default=0)
    colicas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Cólicas", default=0)
    hematomas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Hematomas", default=0)
    obesidade = models.IntegerField(choices=NUM_CHOICES, verbose_name="Obesidade", default=0)
    pernas_inchadas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Pernas inchadas", default=0)
    vasos_sanguineos_inchados = models.IntegerField(choices=NUM_CHOICES, verbose_name="Vasos sanguíneos inchados", default=0)
    rosto_olhos_inchados = models.IntegerField(choices=NUM_CHOICES, verbose_name="Rosto e/ou olhos inchados", default=0)
    tireoide_alargada = models.IntegerField(choices=NUM_CHOICES, verbose_name="Tireoide alargada", default=0)
    unhas_frageis = models.IntegerField(choices=NUM_CHOICES, verbose_name="Unhas frágeis", default=0)
    extremidades_inchadas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Extremidades inchadas", default=0)
    fome_excessiva = models.IntegerField(choices=NUM_CHOICES, verbose_name="Fome excessiva", default=0)
    contatos_extra_conjungais = models.IntegerField(choices=NUM_CHOICES, verbose_name="Relações extraconjugais", default=0)
    labios_secos_formigamento = models.IntegerField(choices=NUM_CHOICES, verbose_name="Lábios secos e/ou com formigamento", default=0)
    disartria = models.IntegerField(choices=NUM_CHOICES, verbose_name="Disartria", default=0)
    dor_joelhos = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor nos joelhos", default=0)
    dor_quadril = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor nos quadris", default=0)
    fraqueza_muscular = models.IntegerField(choices=NUM_CHOICES, verbose_name="Fraqueza muscular", default=0)
    pescoco_rigido = models.IntegerField(choices=NUM_CHOICES, verbose_name="Pescoço rígido", default=0)
    inchaco_juntas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Inchaço nas juntas", default=0)
    rigidez_movimento = models.IntegerField(choices=NUM_CHOICES, verbose_name="Rigidez no movimento", default=0)
    movimento_girando = models.IntegerField(choices=NUM_CHOICES, verbose_name="Sensação de estar tudo girando", default=0)
    perda_equilibrio = models.IntegerField(choices=NUM_CHOICES, verbose_name="Perda de equilíbrio", default=0)
    instabilidade = models.IntegerField(choices=NUM_CHOICES, verbose_name="Instabilidade", default=0)
    fraqueza_um_lado_corpo = models.IntegerField(choices=NUM_CHOICES, verbose_name="Fraqueza em um lado do corpo", default=0)
    perda_olfato = models.IntegerField(choices=NUM_CHOICES, verbose_name="Perda de olfato", default=0)
    desconforto_bexiga = models.IntegerField(choices=NUM_CHOICES, verbose_name="Desconforto na bexiga", default=0)
    mau_cheiro_urina = models.IntegerField(choices=NUM_CHOICES, verbose_name="Mau cheiro na urina", default=0)
    vontade_urina_continua = models.IntegerField(choices=NUM_CHOICES, verbose_name="Vontade contínua de urinar", default=0)
    qtd_excessiva_gases = models.IntegerField(choices=NUM_CHOICES, verbose_name="Quantidade excessiva de gases", default=0)
    comichao_interno = models.IntegerField(choices=NUM_CHOICES, verbose_name="Comichão interno", default=0)
    tifo = models.IntegerField(choices=NUM_CHOICES, verbose_name="Tifo", default=0)
    depressao = models.IntegerField(choices=NUM_CHOICES, verbose_name="Depressão", default=0)
    irritabilidade = models.IntegerField(choices=NUM_CHOICES, verbose_name="Irritabilidade", default=0)
    dor_muscular = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor muscular", default=0)
    inabilidade_pensar_claramente_ou_concentrar = models.IntegerField(choices=NUM_CHOICES, verbose_name="Incapacidade de pensar claramente e/ou se concentrar", default=0)
    manchas_vermelhas_corpo = models.IntegerField(choices=NUM_CHOICES, verbose_name="Manchas vermelhas pelo corpo", default=0)
    dor_barriga = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor de barriga", default=0)
    menstruacao_anormal = models.IntegerField(choices=NUM_CHOICES, verbose_name="Menstruação anormal", default=0)
    discromias = models.IntegerField(choices=NUM_CHOICES, verbose_name="Discromias", default=0)
    olhos_lacrimejantes = models.IntegerField(choices=NUM_CHOICES, verbose_name="Olhos lacrimejantes", default=0)
    aumento_apetite = models.IntegerField(choices=NUM_CHOICES, verbose_name="Aumento do apetite", default=0)
    poliuria = models.IntegerField(choices=NUM_CHOICES, verbose_name="Poliúria", default=0)
    historico_familiar = models.IntegerField(choices=NUM_CHOICES, verbose_name="Histórico familiar de sintomas parecidos", default=0)
    escarro_mucos = models.IntegerField(choices=NUM_CHOICES, verbose_name="Escarro com mucos", default=0)
    escarro_avermelhado_marrom = models.IntegerField(choices=NUM_CHOICES, verbose_name="Escarro avermelhado e marrom (cor de ferrugem)", default=0)
    falta_concentracao = models.IntegerField(choices=NUM_CHOICES, verbose_name="Falta de concentração", default=0)
    perturbacoes_visuais = models.IntegerField(choices=NUM_CHOICES, verbose_name="Perturbações visuais", default=0)
    recebeu_transfusao_sangue = models.IntegerField(choices=NUM_CHOICES, verbose_name="Recebeu transfusão de sangue recentemente", default=0)
    recebeu_injecoes_nao_esterilizadas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Recebeu injeções não esterilizadas", default=0)
    coma = models.IntegerField(choices=NUM_CHOICES, verbose_name="Coma", default=0)
    sangramento_estomacal = models.IntegerField(choices=NUM_CHOICES, verbose_name="Sangramento estomacal", default=0)
    estufamento_abdomen = models.IntegerField(choices=NUM_CHOICES, verbose_name="Estufamento do abdômen", default=0)
    historico_consumo_alcool = models.IntegerField(choices=NUM_CHOICES, verbose_name="Histórico de alcoolismo", default=0)
    hipervolemia = models.IntegerField(choices=NUM_CHOICES, verbose_name="Hipervolemia", default=0)
    sangue_no_escarro = models.IntegerField(choices=NUM_CHOICES, verbose_name="Sangue no escarro", default=0)
    veias_proeminentes_panturrilha = models.IntegerField(choices=NUM_CHOICES, verbose_name="Veias proeminentes na panturrilha", default=0)
    palpitacoes = models.IntegerField(choices=NUM_CHOICES, verbose_name="Palpitações", default=0)
    dor_caminhar = models.IntegerField(choices=NUM_CHOICES, verbose_name="Dor ao caminhar", default=0)
    espinhas_cheias_pus = models.IntegerField(choices=NUM_CHOICES, verbose_name="Espinhas cheias de pus", default=0)
    cravos = models.IntegerField(choices=NUM_CHOICES, verbose_name="Cravos", default=0)
    cicatrizes = models.IntegerField(choices=NUM_CHOICES, verbose_name="Cicatrizes (de espinhas)", default=0)
    descamacao_pele = models.IntegerField(choices=NUM_CHOICES, verbose_name="Descamação da pele", default=0)
    exposicao_poeira_prata = models.IntegerField(choices=NUM_CHOICES, verbose_name="Exposição recente à poeira de prata", default=0)
    pequenas_cavidades_unhas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Pequenas cavidades (buracos) nas unhas", default=0)
    unhas_inflamadas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Unhas inflamadas", default=0)
    bolhas = models.IntegerField(choices=NUM_CHOICES, verbose_name="Bolhas", default=0)
    vermelhidao_ao_redor_nariz = models.IntegerField(choices=NUM_CHOICES, verbose_name="Vermelhidão ao redor do nariz", default=0)
    casca_ferida_amarela = models.IntegerField(choices=NUM_CHOICES, verbose_name="Casca de ferida amarela", default=0)
    prognostico = models.CharField(max_length=100, verbose_name="Prognóstico")

    #class Meta:
    #    verbose_name = _("")
    #    verbose_name_plural = _("s")

    def __str__(self):
        return self.prognostico
