import pandas as pd
from prognosticos.models import PrognosticoData

#Cadastrando predições de prognósticos

PrognosticoData.objects.all()

df_prog = pd.read_csv('data/data_doencas.csv', sep=';', index_col=None, encoding='latin-1')


for i in range(len(df_prog)):
    prog = PrognosticoData()
    
    prog.comichao = df_prog["comichao"][i]
    prog.erupcao_cutanea = df_prog["erupcao_cutanea"][i]
    prog.erupcoes_cutaneas_nodais = df_prog["erupcoes_cutaneas_nodais"][i]
    prog.espirros_continuos = df_prog["espirros_continuos"][i]
    prog.calafrios = df_prog["calafrios"][i]
    prog.arrepios = df_prog["arrepios"][i]
    prog.dor_juntas = df_prog["dor_juntas"][i]
    prog.dor_estomago = df_prog["dor_estomago"][i]
    prog.acidez = df_prog["acidez"][i]
    prog.ulceras_lingua = df_prog["ulceras_lingua"][i]
    prog.desgaste_muscular = df_prog["desgaste_muscular"][i]
    prog.vomito = df_prog["vomito"][i]
    prog.queimacao_urinar = df_prog["queimacao_urinar"][i]
    prog.sangue_urina = df_prog["sangue_urina"][i]
    prog.fadiga = df_prog["fadiga"][i]
    prog.ganho_peso = df_prog["ganho_peso"][i]
    prog.ansiedade = df_prog["ansiedade"][i]
    prog.maos_pes_frios = df_prog["maos_pes_frios"][i]
    prog.mudanca_humor = df_prog["mudanca_humor"][i]
    prog.perda_peso = df_prog["perda_peso"][i]
    prog.inquietacao = df_prog["inquietacao"][i]
    prog.letargia = df_prog["letargia"][i]
    prog.mancha_garganta = df_prog["mancha_garganta"][i]
    prog.nivel_acucar_irregular = df_prog["nivel_acucar_irregular"][i]
    prog.tosse = df_prog["tosse"][i]
    prog.febre_alta = df_prog["febre_alta"][i]
    prog.olhos_fundos = df_prog["olhos_fundos"][i]
    prog.falta_de_ar = df_prog["falta_de_ar"][i]
    prog.suor = df_prog["suor"][i]
    prog.desidratacao = df_prog["desidratacao"][i]
    prog.indigestao = df_prog["indigestao"][i]
    prog.dor_cabeca = df_prog["dor_cabeca"][i]
    prog.pele_amarelada = df_prog["pele_amarelada"][i]
    prog.urina_escura = df_prog["urina_escura"][i]
    prog.nausea = df_prog["nausea"][i]
    prog.perda_apetite = df_prog["perda_apetite"][i]
    prog.dor_atras_olhos = df_prog["dor_atras_olhos"][i]
    prog.dor_costas = df_prog["dor_costas"][i]
    prog.constipacao = df_prog["constipacao"][i]
    prog.dor_abdominal = df_prog["dor_abdominal"][i]
    prog.diarreia = df_prog["diarreia"][i]
    prog.febre_suave = df_prog["febre_suave"][i]
    prog.urina_amarela = df_prog["urina_amarela"][i]
    prog.amarelamento_olhos = df_prog["amarelamento_olhos"][i]
    prog.falencia_aguda_figado = df_prog["falencia_aguda_figado"][i]
    prog.inchaco_estomago = df_prog["inchaco_estomago"][i]
    prog.linfonodos_aumentados = df_prog["linfonodos_aumentados"][i]
    prog.mal_estar = df_prog["mal_estar"][i]
    prog.visao_borrada_distorcida = df_prog["visao_borrada_distorcida"][i]
    prog.catarro = df_prog["catarro"][i]
    prog.irritacao_garganta = df_prog["irritacao_garganta"][i]
    prog.vermelhidao_olhos = df_prog["vermelhidao_olhos"][i]
    prog.sinusite = df_prog["sinusite"][i]
    prog.nariz_escorrendo = df_prog["nariz_escorrendo"][i]
    prog.nariz_entupido = df_prog["nariz_entupido"][i]
    prog.dor_peito = df_prog["dor_peito"][i]
    prog.fraqueza_membros = df_prog["fraqueza_membros"][i]
    prog.taquicardia = df_prog["taquicardia"][i]
    prog.dor_ao_evacuar = df_prog["dor_ao_evacuar"][i]
    prog.dor_regiao_anal = df_prog["dor_regiao_anal"][i]
    prog.sangue_fezes = df_prog["sangue_fezes"][i]
    prog.irritacao_anus = df_prog["irritacao_anus"][i]
    prog.dor_pescoco = df_prog["dor_pescoco"][i]
    prog.tontura = df_prog["tontura"][i]
    prog.colicas = df_prog["colicas"][i]
    prog.hematomas = df_prog["hematomas"][i]
    prog.obesidade = df_prog["obesidade"][i]
    prog.pernas_inchadas = df_prog["pernas_inchadas"][i]
    prog.vasos_sanguineos_inchados = df_prog["vasos_sanguineos_inchados"][i]
    prog.rosto_olhos_inchados = df_prog["rosto_olhos_inchados"][i]
    prog.tireoide_alargada = df_prog["tireoide_alargada"][i]
    prog.unhas_frageis = df_prog["unhas_frageis"][i]
    prog.extremidades_inchadas = df_prog["extremidades_inchadas"][i]
    prog.fome_excessiva = df_prog["fome_excessiva"][i]
    prog.contatos_extra_conjungais = df_prog["contatos_extra_conjungais"][i]
    prog.labios_secos_formigamento = df_prog["labios_secos_formigamento"][i]
    prog.disartria = df_prog["disartria"][i]
    prog.dor_joelhos = df_prog["dor_joelhos"][i]
    prog.dor_quadril = df_prog["dor_quadril"][i]
    prog.fraqueza_muscular = df_prog["fraqueza_muscular"][i]
    prog.pescoco_rigido = df_prog["pescoco_rigido"][i]
    prog.inchaco_juntas = df_prog["inchaco_juntas"][i]
    prog.rigidez_movimento = df_prog["rigidez_movimento"][i]
    prog.movimento_girando = df_prog["movimento_girando"][i]
    prog.perda_equilibrio = df_prog["perda_equilibrio"][i]
    prog.instabilidade = df_prog["instabilidade"][i]
    prog.fraqueza_um_lado_corpo = df_prog["fraqueza_um_lado_corpo"][i]
    prog.perda_olfato = df_prog["perda_olfato"][i]
    prog.desconforto_bexiga = df_prog["desconforto_bexiga"][i]
    prog.mau_cheiro_urina = df_prog["mau_cheiro_urina"][i]
    prog.vontade_urina_continua = df_prog["vontade_urina_continua"][i]
    prog.qtd_excessiva_gases = df_prog["qtd_excessiva_gases"][i]
    prog.comichao_interno = df_prog["comichao_interno"][i]
    prog.tifo = df_prog["tifo"][i]
    prog.depressao = df_prog["depressao"][i]
    prog.irritabilidade = df_prog["irritabilidade"][i]
    prog.dor_muscular = df_prog["dor_muscular"][i]
    prog.inabilidade_pensar_claramente_ou_concentrar = df_prog["inabilidade_pensar_claramente_ou_concentrar"][i]
    prog.manchas_vermelhas_corpo = df_prog["manchas_vermelhas_corpo"][i]
    prog.dor_barriga = df_prog["dor_barriga"][i]
    prog.menstruacao_anormal = df_prog["menstruacao_anormal"][i]
    prog.discromias = df_prog["discromias"][i]
    prog.olhos_lacrimejantes = df_prog["olhos_lacrimejantes"][i]
    prog.aumento_apetite = df_prog["aumento_apetite"][i]
    prog.poliuria = df_prog["poliuria"][i]
    prog.historico_familiar = df_prog["historico_familiar"][i]
    prog.escarro_mucos = df_prog["escarro_mucos"][i]
    prog.escarro_avermelhado_marrom = df_prog["escarro_avermelhado_marrom"][i]
    prog.falta_concentracao = df_prog["falta_concentracao"][i]
    prog.perturbacoes_visuais = df_prog["perturbacoes_visuais"][i]
    prog.recebeu_transfusao_sangue = df_prog["recebeu_transfusao_sangue"][i]
    prog.recebeu_injecoes_nao_esterilizadas = df_prog["recebeu_injecoes_nao_esterilizadas"][i]
    prog.coma = df_prog["coma"][i]
    prog.sangramento_estomacal = df_prog["sangramento_estomacal"][i]
    prog.estufamento_abdomen = df_prog["estufamento_abdomen"][i]
    prog.historico_consumo_alcool = df_prog["historico_consumo_alcool"][i]
    prog.hipervolemia = df_prog["hipervolemia"][i]
    prog.sangue_no_escarro = df_prog["sangue_no_escarro"][i]
    prog.veias_proeminentes_panturrilha = df_prog["veias_proeminentes_panturrilha"][i]
    prog.palpitacoes = df_prog["palpitacoes"][i]
    prog.dor_caminhar = df_prog["dor_caminhar"][i]
    prog.espinhas_cheias_pus = df_prog["espinhas_cheias_pus"][i]
    prog.cravos = df_prog["cravos"][i]
    prog.cicatrizes = df_prog["cicatrizes"][i]
    prog.descamacao_pele = df_prog["descamacao_pele"][i]
    prog.exposicao_poeira_prata = df_prog["exposicao_poeira_prata"][i]
    prog.pequenas_cavidades_unhas = df_prog["pequenas_cavidades_unhas"][i]
    prog.unhas_inflamadas = df_prog["unhas_inflamadas"][i]
    prog.bolhas = df_prog["bolhas"][i]
    prog.vermelhidao_ao_redor_nariz = df_prog["vermelhidao_ao_redor_nariz"][i]
    prog.casca_ferida_amarela = df_prog["casca_ferida_amarela"][i]
    prog.prognostico = df_prog["prognostico"][i]

    prog.save()
    print('Salvou: ' + str(prog))
