# Generated by Django 3.0.5 on 2020-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prognosticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prognosticodata',
            name='acidez',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Acidez'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='amarelamento_olhos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Amarelamento dos olhos'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='ansiedade',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Ansiedade'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='arrepios',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Arrepios'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='aumento_apetite',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Aumento do apetite'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='bolhas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Bolhas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='calafrios',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Calafrios'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='casca_ferida_amarela',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Casca de ferida amarela'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='catarro',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Catarro'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='cicatrizes',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Cicatrizes (de espinhas)'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='colicas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Cólicas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='coma',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Coma'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='comichao',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Comichão'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='comichao_interno',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Comichão interno'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='constipacao',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Constipação'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='contatos_extra_conjungais',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Relações extraconjugais'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='cravos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Cravos'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='depressao',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Depressão'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='descamacao_pele',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Descamação da pele'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='desconforto_bexiga',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Desconforto na bexiga'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='desgaste_muscular',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Desgaste muscular'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='desidratacao',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Desidratação'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='diarreia',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Diarreia'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='disartria',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Disartria'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='discromias',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Discromias'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_abdominal',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor abdominal'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_ao_evacuar',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor ao evacuar'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_atras_olhos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor atrás dos olhos'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_barriga',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor de barriga'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_cabeca',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor de cabeça'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_caminhar',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor ao caminhar'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_costas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor nas costas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_estomago',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor no estômago'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_joelhos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor nos joelhos'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_juntas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor nas juntas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_muscular',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor muscular'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_peito',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor no peito'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_pescoco',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor no pescoço'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_quadril',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor nos quadris'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='dor_regiao_anal',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Dor na região anal'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='erupcao_cutanea',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Erupção cutânea'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='erupcoes_cutaneas_nodais',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Erupções cutâneas nodais'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='escarro_avermelhado_marrom',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Escarro avermelhado e marrom (cor de ferrugem)'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='escarro_mucos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Escarro com mucos'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='espinhas_cheias_pus',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Espinhas cheias de pus'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='espirros_continuos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Espirros contínuos'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='estufamento_abdomen',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Estufamento do abdômen'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='exposicao_poeira_prata',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Exposição recente à poeira de prata'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='extremidades_inchadas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Extremidades inchadas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='fadiga',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Fadiga'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='falencia_aguda_figado',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Falência aguda do fígado'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='falta_concentracao',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Falta de concentração'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='falta_de_ar',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Falta de ar'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='febre_alta',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Febre alta'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='febre_suave',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Febre suave'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='fome_excessiva',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Fome excessiva'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='fraqueza_membros',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Fraqueza nos membros (superiores e/ou inferiores)'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='fraqueza_muscular',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Fraqueza muscular'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='fraqueza_um_lado_corpo',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Fraqueza em um lado do corpo'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='ganho_peso',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Ganho de peso'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='hematomas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Hematomas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='hipervolemia',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Hipervolemia'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='historico_consumo_alcool',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Histórico de alcoolismo'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='historico_familiar',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Histórico familiar de sintomas parecidos'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='inabilidade_pensar_claramente_ou_concentrar',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Incapacidade de pensar claramente e/ou se concentrar'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='inchaco_estomago',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Inchaço no estômago'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='inchaco_juntas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Inchaço nas juntas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='indigestao',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Indigestão'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='inquietacao',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Inquietação'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='instabilidade',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Instabilidade'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='irritabilidade',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Irritabilidade'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='irritacao_anus',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Irritação no ânus'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='irritacao_garganta',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Irritação na garganta'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='labios_secos_formigamento',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Lábios secos e/ou com formigamento'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='letargia',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Letargia'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='linfonodos_aumentados',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Linfonodos aumentados'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='mal_estar',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Mal estar'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='mancha_garganta',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Manchas (brancas) na garganta'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='manchas_vermelhas_corpo',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Manchas vermelhas pelo corpo'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='maos_pes_frios',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Mãos e pés frios'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='mau_cheiro_urina',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Mau cheiro na urina'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='menstruacao_anormal',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Menstruação anormal'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='movimento_girando',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Sensação de estar tudo girando'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='mudanca_humor',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Mudança de humor'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='nariz_entupido',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Nariz entupido'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='nariz_escorrendo',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Nariz escorrendo'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='nausea',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Náusea'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='nivel_acucar_irregular',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Nível de açúcar irregular'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='obesidade',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Obesidade'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='olhos_fundos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Olhos fundos'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='olhos_lacrimejantes',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Olhos lacrimejantes'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='palpitacoes',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Palpitações'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='pele_amarelada',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Pele amarelada'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='pequenas_cavidades_unhas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Pequenas cavidades (buracos) nas unhas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='perda_apetite',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Perda de apetite'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='perda_equilibrio',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Perda de equilíbrio'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='perda_olfato',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Perda de olfato'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='perda_peso',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Perda de peso'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='pernas_inchadas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Pernas inchadas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='perturbacoes_visuais',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Perturbações visuais'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='pescoco_rigido',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Pescoço rígido'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='poliuria',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Poliúria'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='qtd_excessiva_gases',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Quantidade excessiva de gases'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='queimacao_urinar',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Queimação ao urinar'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='recebeu_injecoes_nao_esterilizadas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Recebeu injeções não esterilizadas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='recebeu_transfusao_sangue',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Recebeu transfusão de sangue recentemente'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='rigidez_movimento',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Rigidez no movimento'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='rosto_olhos_inchados',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Rosto e/ou olhos inchados'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='sangramento_estomacal',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Sangramento estomacal'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='sangue_fezes',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Sangue nas fezes'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='sangue_no_escarro',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Sangue no escarro'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='sangue_urina',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Sangue na urina'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='sinusite',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Sinusite'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='suor',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Suor'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='taquicardia',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Taquicardia'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='tifo',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Tifo'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='tireoide_alargada',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Tireoide alargada'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='tontura',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Tontura'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='tosse',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Tosse'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='ulceras_lingua',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Úlceras na língua'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='unhas_frageis',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Unhas frágeis'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='unhas_inflamadas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Unhas inflamadas'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='urina_amarela',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Urina amarela'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='urina_escura',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Urina escura'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='vasos_sanguineos_inchados',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Vasos sanguíneos inchados'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='veias_proeminentes_panturrilha',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Veias proeminentes na panturrilha'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='vermelhidao_ao_redor_nariz',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Vermelhidão ao redor do nariz'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='vermelhidao_olhos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Vermelhidão nos olhos'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='visao_borrada_distorcida',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Visão borrada e/ou distorcida'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='vomito',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Vômito'),
        ),
        migrations.AlterField(
            model_name='prognosticodata',
            name='vontade_urina_continua',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], verbose_name='Vontade contínua de urinar'),
        ),
    ]
